create table if not exists technician_tasks (
  id bigint generated by default as identity primary key,
  technician_id bigint references technicians(id) on delete cascade,
  description text not null,
  status text check (status in ('pending', 'completed')) default 'pending',
  due_date date,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

-- RLS Policies
alter table technician_tasks enable row level security;

-- Dealer can view/create/update/delete tasks they created or for their technicians
create policy "Dealers can manage their technicians' tasks"
  on technician_tasks
  for all
  using (
    auth.uid() = created_by 
    or technician_id in (select id from technicians where user_id = auth.uid())
  );

-- Technicians can view and update their own tasks
create policy "Technicians can view their own tasks"
  on technician_tasks
  for select
  using (
    technician_id in (select id from technicians where profile_id = auth.uid())
  );

create policy "Technicians can update their own tasks"
  on technician_tasks
  for update
  using (
    technician_id in (select id from technicians where profile_id = auth.uid())
  );
